version: '3.8'

services:
  paste-create-service:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/paste_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  mysql:
    image: mysql:8
    container_name: paste-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paste_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
