global:
  scrape_interval: 15s  # Mặc định: 1 lần mỗi 15 giây

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']